Delete http://localhost:3001/api/blogs/673c831aa80325b81824a86a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpbmciLCJpZCI6IjY3M2M4MDY3Zjc5YWJkY2NmYzk3NmNmYSIsImlhdCI6MTczMjAyMTE2N30.iojlzOHz6bCkv0uKkuqr4r5sqchYJb-dlbOGAQNKZTE
